### ISSUE TITLE
Class of inputs/outputs,Activity Diagram, Seq Diagram - register 

### ISSUE THREAD

**Issue by 5731075221-PM** [we-inc/mms-sesusa#3]
**Use case ลงทะเบียน**
- ประเภทของการลงทะเบียนควรเป็น ENUM มากกว่า Character
- ยืนยันรหัสผ่าน เงื่อนไข Validity ควรระบุว่าจำเป็นต้องตรงกับ รหัสผ่าน

**Activity Diagram ลงทะเบียน**
- เงื่อนไข ภายในเวลาที่กำหนดควรระบุเวลาที่ชัดเจน

**Sequence Diagram ลงทะเบียน**
- chooseTypeoOUserAccount() , messageToSend(0 พิมพ์ผิด

**Comment by 5731055721-TM** [comment]
แก้ไขเรียบร้อยแล้วค่ะ
