### ISSUE TITLE
Front end : Register

### ISSUE THREAD

**Issue by 5731110521-SP** [we-inc/mms-sesusa#41]
- [ ] UI
  - [ ] ตรวจ username ซ้ำ
  - [ ] invalid input

**Comment by 5731079821-PP** [comment]
อันนี้ไม่ได้มีคนทำไปแล้วหรอ @5731110521-SP

**Comment by 5731110521-SP** [comment]
กำลังทำอันใหม่
@5731075221-PM หรือ @5731078121-PT เริ่มทำแล้ว assignตัวเองด้วย 👆
