### ISSUE TITLE
Activity Diagram - เพิ่มรายการ, Use case desc - จัดการรายการ, acceptance criteria

### ISSUE THREAD

**Issue by 5731075221-PM** [we-inc/mms-sesusa#5]
**Activity Diagram เพิ่มรายการเพื่อรับฝากสินค้า**
- เส้นของลูกศรมีการทับซ้อนกันมาก ทำให้ดูไม่ชัดเจน อ่านยาก
- จากแผนภาพ ทำให้สามารถเกิดกรณีที่ผู้ใช้ เพื่อชื่อเมืองที่จะไปมากกว่า 1 เมือง แต่เพิ่มชื่อสินค้าที่มี
อยู่เฉพาะในบางเมือง ซึ่งอาจทำให้ลูกค้าเกิดความสับสน เช่น
- เพิ่มประเทศเกาหลี และประเทศจีน
- เพิ่มสินค้ากิมจิ
- เพิ่มสินค้าโชยุ
- ลูกค้าอาจะเข้าใจผิดว่า สินค้ากิมจิเป็นของประเทศญี่ปุ่น
ดังนั้น ควรจัดลำดับขั้นตอนการเพิ่มรายการเพื่อรับฝากสินค้าให้ลดความสับสนลง

**Use case desc จัดการสถานะสินค้า**
- ขาด Precondition ซึ่งคือการสั่งซื้อสินค้า และชำระเงินแล้ว

**Acceptance Criteria**
ตารางแสดงเกณฑ์การพิจารณาตามความต้องการเชิงคุณภาพ
1. ทดสอบการติดต่อกับผู้ใช้โดยใช้ภาพสัญลักษณ์ ไม่ใช่Qualitative Requirement
2. Smoke testing ไม่ใช่ เกณฑ์การพิจารณาตามความต้องการเชิงคุณภาพ
ตารางแสดงเกณฑ์การพิจารณาตามความต้องการเชิงคุณภาพ
3.
ควรจะอธิบายผลลัพธ์ของการชำระเงินให้ละเอียดกว่านี้ตามที่ได้เขียนไว้ใน
Functional Requirement เช่น ผู้ใช้สามารถชำระเงินจากใบแจ้งการชำระเงินได้และระบบจะออก
ใบยืนยันชำระสินค้าให้
4. ขาดเกณฑ์ (อิงจาก Functional Requirements) ดังนี้
a. ติดตามสินค้า (Tracking)
b. การรีวิวการให้บริการ (Review)
c. ประกาศ (Product announcement)
d. อัพเดตสถานะสินค้า (Update order status)
e. ตรวจรายการสินค้าที่ได้รับฝาก (Order checking)

**Comment by bbeebah** [comment]
@5731075221-PM  ฝากเชคด้วยนะคะะะ
