### ISSUE TITLE
Class of inputs/outputs - แก้ไขสินค้า, Activity Diagram - แสดงผล, Document

### ISSUE THREAD

**Issue by 5731075221-PM** [we-inc/mms-sesusa#6]
**Use case อัพเดทสถานะสินค้า**
- ควรระบุสินค้าที่ต้องการตั้งสถานะ → Input: สินค้า Type: Item

**Document**
- พิมข้อความผิดไวยากรณ์ ‘ The Requirement Specification Document เป็นเอกสารที่ อธิบาย
ของระบบ ที่จะพัฒนาขึ้น’
- ควรเพิ่มเติมรายละเอียดในส่วนของ User Manual ว่าเป็น ManualสำหรับActorใดบ้าง

**activity diagram and sequence diagram**
- แสดงผล ทำใหม่

**Comment by palidaa** [comment]
แก้ไขแล้วค่ะ
