### ISSUE TITLE
Activity Diagram - แก้ไขประวัติ, Use case and Use Case desc & Seq Diagram - ให้คะแนน

### ISSUE THREAD

**Issue by 5731075221-PM** [we-inc/mms-sesusa#7]
**Activity Diagram แก้ไขข้อมูลในระบบ**
- เงื่อนไขบน [ใช่] กับ [ไม่ใช่] มีความกำกวม ไม่เข้าใจความหมายที่แน่ชัด

**Use Case**
ให้คะแนน ควรมีความสัมพันธ์แบบincludeกับ แสดงความคิดเห็น เพราะผู้ใช้จำเป็นต้องแสดงความ
คิดเห็นก่อน จึงจะให้คะแนนได้ และจำเป็นต้องกระทำต่อเนื่องกันทันที

**Use case description**
Use case ให้คะแนน
- Postcondition ผู้ประเมิน สะกดผิด
- ถ้าหากผู้ฝากซื้อไม่พอใจเองและให้คะแนนตํ่ามากเกินจริง จนผู้ฝากซื้อโดนระงับบัญชีผู้ใช้มีการจัดการ
อย่างไร เพราะดูเหมือนว่าระบบจะทำงานคำนวณคะแนนอัตโนมัติ

**Sequence Diagram ให้คะแนน**
- Actor :WAANSystem เป็นคนให้คะแนน?

**Comment by 5731079821-PP** [comment]
*************************เพิ่ม*********************************
แก้ไขระบบให้คะแนน ทั้ง functional requirement + Use Case Diagram + Use Case Description + Activity Diagram
  - ให้คะแนนผู้ใช้งาน
  - ให้คะแนนผู้ฝากซื้อ
  - ให้คะแนนผู้รับฝากซื้อ

**Comment by 5731079821-PP** [comment]
แก้เรียบร้อยแล้วนะคะ @5731110521-SP  ดูเผื่อมีต้องทำให้สอดคล้องกันตรง สถานะการฝากซื้อ

**Comment by 5731079821-PP** [comment]
แก้ Class +Sequence ใหม่ละนะคะ
